baseURL: https://stornado.github.io/head-first-verilog/

defaultContentLanguage: zh-cn
defaultContentLanguageInSubdir: false

languages:
  zh-cn:
    title: 仲夏园
    description: 生命就是用求知的欲望燃烧自己
    contentDir: content/cn
    languageName: 中文
    languageCode: zh-cn
    weight: 1

enableGitInfo: true
enableRobotsTXT: true

params:
  copyright: 仲夏叶
  privacy_policy: "/head-first-verilog/privacy-policy/"
  repo: &repo https://github.com/stornado/head-first-verilog
  github_repo: *repo
  github_project_repo: *repo
  github_branch: main
  branch: main
  locale: zh_CN
  ui:
    footer_about_disable: true
    navbar_logo: true
    navbar_translucent_over_cover_disable: true
    sidebar_menu_compact: true

  offlineSearch: true
  prism_syntax_highlighting: true

  links:
    developer:
      - name: GitHub
        url: https://github.com/stornado
        icon: fab fa-github

  taxonomy:
    taxonomyCloud: [tags, categories]
    taxonomyCloudTitle: ["Tag Cloud", "Categories"]
    taxonomyPageHeader: [tags, categories]

  mermaid:
    enable: true
  katex:
    enable: true

taxonomies:
  tag: tags
  category: categories

markup:
  goldmark:
    renderer: { unsafe: true }
  highlight:
    style: tango
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false

imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

outputs:
  home: [HTML]
  section: [HTML, RSS, print]
  taxonomy: [HTML]
  term: [HTML]

module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies

pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango

permalinks:
  blog: "/:section/:year/:month/:day/:slug/"
